// GENERATED by scripts/genCostData.mjs — do not edit by hand.
// Source: World Bank Open Data (https://data.worldbank.org), CC BY 4.0.
// priceLevel = consumer-PPP-or-GDP-PPP factor / market exchange rate, US = 1.0
// (< 1 cheaper than the US, > 1 pricier). Indicators: PA.NUS.PRVT.PP (preferred),
// PA.NUS.PPP (fallback), PA.NUS.FCRF. Each country uses its latest year where both
// inputs exist. 201 countries.

export type CountryPriceLevel = {
  iso3: string;
  iso2: string;
  /** Price level relative to the United States (US = 1.0). */
  priceLevel: number;
  /** The data year this ratio is computed from. */
  year: number;
  /** Which PPP factor was used: household-consumption ("consumer") or GDP ("gdp"). */
  pppSource: "consumer" | "gdp";
};

// Keyed by case/accent-folded country name (see fold() in lib/cost.ts).
export const COUNTRY_PRICE_LEVELS: Record<string, CountryPriceLevel> = {
  "afghanistan": {
    "iso3": "AFG",
    "iso2": "AF",
    "priceLevel": 0.206,
    "year": 2020,
    "pppSource": "consumer"
  },
  "albania": {
    "iso3": "ALB",
    "iso2": "AL",
    "priceLevel": 0.492,
    "year": 2024,
    "pppSource": "consumer"
  },
  "algeria": {
    "iso3": "DZA",
    "iso2": "DZ",
    "priceLevel": 0.315,
    "year": 2024,
    "pppSource": "consumer"
  },
  "american samoa": {
    "iso3": "ASM",
    "iso2": "AS",
    "priceLevel": 0.903,
    "year": 2021,
    "pppSource": "consumer"
  },
  "andorra": {
    "iso3": "AND",
    "iso2": "AD",
    "priceLevel": 0.756,
    "year": 2021,
    "pppSource": "consumer"
  },
  "angola": {
    "iso3": "AGO",
    "iso2": "AO",
    "priceLevel": 0.358,
    "year": 2024,
    "pppSource": "consumer"
  },
  "antigua and barbuda": {
    "iso3": "ATG",
    "iso2": "AG",
    "priceLevel": 0.822,
    "year": 2024,
    "pppSource": "consumer"
  },
  "argentina": {
    "iso3": "ARG",
    "iso2": "AR",
    "priceLevel": 0.453,
    "year": 2021,
    "pppSource": "consumer"
  },
  "armenia": {
    "iso3": "ARM",
    "iso2": "AM",
    "priceLevel": 0.401,
    "year": 2024,
    "pppSource": "consumer"
  },
  "aruba": {
    "iso3": "ABW",
    "iso2": "AW",
    "priceLevel": 0.845,
    "year": 2021,
    "pppSource": "consumer"
  },
  "australia": {
    "iso3": "AUS",
    "iso2": "AU",
    "priceLevel": 0.942,
    "year": 2024,
    "pppSource": "consumer"
  },
  "austria": {
    "iso3": "AUT",
    "iso2": "AT",
    "priceLevel": 0.78,
    "year": 2024,
    "pppSource": "consumer"
  },
  "azerbaijan": {
    "iso3": "AZE",
    "iso2": "AZ",
    "priceLevel": 0.311,
    "year": 2024,
    "pppSource": "consumer"
  },
  "bahamas, the": {
    "iso3": "BHS",
    "iso2": "BS",
    "priceLevel": 1.107,
    "year": 2024,
    "pppSource": "consumer"
  },
  "bahrain": {
    "iso3": "BHR",
    "iso2": "BH",
    "priceLevel": 0.502,
    "year": 2024,
    "pppSource": "consumer"
  },
  "bangladesh": {
    "iso3": "BGD",
    "iso2": "BD",
    "priceLevel": 0.285,
    "year": 2024,
    "pppSource": "consumer"
  },
  "barbados": {
    "iso3": "BRB",
    "iso2": "BB",
    "priceLevel": 1.319,
    "year": 2021,
    "pppSource": "consumer"
  },
  "belarus": {
    "iso3": "BLR",
    "iso2": "BY",
    "priceLevel": 0.252,
    "year": 2024,
    "pppSource": "consumer"
  },
  "belgium": {
    "iso3": "BEL",
    "iso2": "BE",
    "priceLevel": 0.814,
    "year": 2024,
    "pppSource": "consumer"
  },
  "belize": {
    "iso3": "BLZ",
    "iso2": "BZ",
    "priceLevel": 0.553,
    "year": 2024,
    "pppSource": "consumer"
  },
  "benin": {
    "iso3": "BEN",
    "iso2": "BJ",
    "priceLevel": 0.329,
    "year": 2024,
    "pppSource": "consumer"
  },
  "bermuda": {
    "iso3": "BMU",
    "iso2": "BM",
    "priceLevel": 1.441,
    "year": 2021,
    "pppSource": "consumer"
  },
  "bhutan": {
    "iso3": "BTN",
    "iso2": "BT",
    "priceLevel": 0.25,
    "year": 2024,
    "pppSource": "consumer"
  },
  "bolivia": {
    "iso3": "BOL",
    "iso2": "BO",
    "priceLevel": 0.336,
    "year": 2024,
    "pppSource": "consumer"
  },
  "bosnia and herzegovina": {
    "iso3": "BIH",
    "iso2": "BA",
    "priceLevel": 0.407,
    "year": 2024,
    "pppSource": "consumer"
  },
  "botswana": {
    "iso3": "BWA",
    "iso2": "BW",
    "priceLevel": 0.392,
    "year": 2024,
    "pppSource": "consumer"
  },
  "brazil": {
    "iso3": "BRA",
    "iso2": "BR",
    "priceLevel": 0.468,
    "year": 2024,
    "pppSource": "consumer"
  },
  "brunei darussalam": {
    "iso3": "BRN",
    "iso2": "BN",
    "priceLevel": 0.406,
    "year": 2024,
    "pppSource": "consumer"
  },
  "bulgaria": {
    "iso3": "BGR",
    "iso2": "BG",
    "priceLevel": 0.422,
    "year": 2024,
    "pppSource": "consumer"
  },
  "burkina faso": {
    "iso3": "BFA",
    "iso2": "BF",
    "priceLevel": 0.329,
    "year": 2024,
    "pppSource": "consumer"
  },
  "burundi": {
    "iso3": "BDI",
    "iso2": "BI",
    "priceLevel": 0.357,
    "year": 2024,
    "pppSource": "consumer"
  },
  "cabo verde": {
    "iso3": "CPV",
    "iso2": "CV",
    "priceLevel": 0.522,
    "year": 2024,
    "pppSource": "consumer"
  },
  "cambodia": {
    "iso3": "KHM",
    "iso2": "KH",
    "priceLevel": 0.363,
    "year": 2024,
    "pppSource": "consumer"
  },
  "cameroon": {
    "iso3": "CMR",
    "iso2": "CM",
    "priceLevel": 0.342,
    "year": 2024,
    "pppSource": "consumer"
  },
  "canada": {
    "iso3": "CAN",
    "iso2": "CA",
    "priceLevel": 0.906,
    "year": 2024,
    "pppSource": "consumer"
  },
  "cayman islands": {
    "iso3": "CYM",
    "iso2": "KY",
    "priceLevel": 1.401,
    "year": 2021,
    "pppSource": "consumer"
  },
  "central african republic": {
    "iso3": "CAF",
    "iso2": "CF",
    "priceLevel": 0.434,
    "year": 2024,
    "pppSource": "consumer"
  },
  "chad": {
    "iso3": "TCD",
    "iso2": "TD",
    "priceLevel": 0.393,
    "year": 2024,
    "pppSource": "consumer"
  },
  "chile": {
    "iso3": "CHL",
    "iso2": "CL",
    "priceLevel": 0.493,
    "year": 2024,
    "pppSource": "consumer"
  },
  "china": {
    "iso3": "CHN",
    "iso2": "CN",
    "priceLevel": 0.493,
    "year": 2024,
    "pppSource": "consumer"
  },
  "colombia": {
    "iso3": "COL",
    "iso2": "CO",
    "priceLevel": 0.379,
    "year": 2024,
    "pppSource": "consumer"
  },
  "comoros": {
    "iso3": "COM",
    "iso2": "KM",
    "priceLevel": 0.555,
    "year": 2024,
    "pppSource": "consumer"
  },
  "congo, dem. rep.": {
    "iso3": "COD",
    "iso2": "CD",
    "priceLevel": 0.467,
    "year": 2021,
    "pppSource": "consumer"
  },
  "congo, rep.": {
    "iso3": "COG",
    "iso2": "CG",
    "priceLevel": 0.383,
    "year": 2024,
    "pppSource": "consumer"
  },
  "costa rica": {
    "iso3": "CRI",
    "iso2": "CR",
    "priceLevel": 0.637,
    "year": 2024,
    "pppSource": "consumer"
  },
  "cote d'ivoire": {
    "iso3": "CIV",
    "iso2": "CI",
    "priceLevel": 0.386,
    "year": 2024,
    "pppSource": "consumer"
  },
  "croatia": {
    "iso3": "HRV",
    "iso2": "HR",
    "priceLevel": 0.535,
    "year": 2024,
    "pppSource": "consumer"
  },
  "curacao": {
    "iso3": "CUW",
    "iso2": "CW",
    "priceLevel": 0.787,
    "year": 2021,
    "pppSource": "consumer"
  },
  "cyprus": {
    "iso3": "CYP",
    "iso2": "CY",
    "priceLevel": 0.639,
    "year": 2024,
    "pppSource": "consumer"
  },
  "czechia": {
    "iso3": "CZE",
    "iso2": "CZ",
    "priceLevel": 0.617,
    "year": 2024,
    "pppSource": "consumer"
  },
  "denmark": {
    "iso3": "DNK",
    "iso2": "DK",
    "priceLevel": 0.981,
    "year": 2024,
    "pppSource": "consumer"
  },
  "djibouti": {
    "iso3": "DJI",
    "iso2": "DJ",
    "priceLevel": 0.545,
    "year": 2021,
    "pppSource": "consumer"
  },
  "dominica": {
    "iso3": "DMA",
    "iso2": "DM",
    "priceLevel": 0.577,
    "year": 2024,
    "pppSource": "consumer"
  },
  "dominican republic": {
    "iso3": "DOM",
    "iso2": "DO",
    "priceLevel": 0.395,
    "year": 2024,
    "pppSource": "consumer"
  },
  "ecuador": {
    "iso3": "ECU",
    "iso2": "EC",
    "priceLevel": 0.45,
    "year": 2024,
    "pppSource": "consumer"
  },
  "egypt, arab rep.": {
    "iso3": "EGY",
    "iso2": "EG",
    "priceLevel": 0.153,
    "year": 2024,
    "pppSource": "consumer"
  },
  "el salvador": {
    "iso3": "SLV",
    "iso2": "SV",
    "priceLevel": 0.48,
    "year": 2024,
    "pppSource": "consumer"
  },
  "equatorial guinea": {
    "iso3": "GNQ",
    "iso2": "GQ",
    "priceLevel": 0.455,
    "year": 2024,
    "pppSource": "consumer"
  },
  "eritrea": {
    "iso3": "ERI",
    "iso2": "ER",
    "priceLevel": 0.345,
    "year": 2021,
    "pppSource": "consumer"
  },
  "estonia": {
    "iso3": "EST",
    "iso2": "EE",
    "priceLevel": 0.699,
    "year": 2024,
    "pppSource": "consumer"
  },
  "eswatini": {
    "iso3": "SWZ",
    "iso2": "SZ",
    "priceLevel": 0.419,
    "year": 2021,
    "pppSource": "consumer"
  },
  "ethiopia": {
    "iso3": "ETH",
    "iso2": "ET",
    "priceLevel": 0.297,
    "year": 2024,
    "pppSource": "consumer"
  },
  "faroe islands": {
    "iso3": "FRO",
    "iso2": "FO",
    "priceLevel": 1.039,
    "year": 2021,
    "pppSource": "consumer"
  },
  "fiji": {
    "iso3": "FJI",
    "iso2": "FJ",
    "priceLevel": 0.408,
    "year": 2024,
    "pppSource": "consumer"
  },
  "finland": {
    "iso3": "FIN",
    "iso2": "FI",
    "priceLevel": 0.853,
    "year": 2024,
    "pppSource": "consumer"
  },
  "france": {
    "iso3": "FRA",
    "iso2": "FR",
    "priceLevel": 0.776,
    "year": 2024,
    "pppSource": "consumer"
  },
  "french polynesia": {
    "iso3": "PYF",
    "iso2": "PF",
    "priceLevel": 1.01,
    "year": 2021,
    "pppSource": "consumer"
  },
  "gabon": {
    "iso3": "GAB",
    "iso2": "GA",
    "priceLevel": 0.467,
    "year": 2024,
    "pppSource": "consumer"
  },
  "gambia, the": {
    "iso3": "GMB",
    "iso2": "GM",
    "priceLevel": 0.287,
    "year": 2024,
    "pppSource": "consumer"
  },
  "georgia": {
    "iso3": "GEO",
    "iso2": "GE",
    "priceLevel": 0.395,
    "year": 2024,
    "pppSource": "consumer"
  },
  "germany": {
    "iso3": "DEU",
    "iso2": "DE",
    "priceLevel": 0.759,
    "year": 2024,
    "pppSource": "consumer"
  },
  "ghana": {
    "iso3": "GHA",
    "iso2": "GH",
    "priceLevel": 0.333,
    "year": 2024,
    "pppSource": "consumer"
  },
  "greece": {
    "iso3": "GRC",
    "iso2": "GR",
    "priceLevel": 0.604,
    "year": 2024,
    "pppSource": "consumer"
  },
  "greenland": {
    "iso3": "GRL",
    "iso2": "GL",
    "priceLevel": 0.873,
    "year": 2021,
    "pppSource": "consumer"
  },
  "grenada": {
    "iso3": "GRD",
    "iso2": "GD",
    "priceLevel": 0.631,
    "year": 2024,
    "pppSource": "consumer"
  },
  "guam": {
    "iso3": "GUM",
    "iso2": "GU",
    "priceLevel": 1.112,
    "year": 2021,
    "pppSource": "consumer"
  },
  "guatemala": {
    "iso3": "GTM",
    "iso2": "GT",
    "priceLevel": 0.448,
    "year": 2024,
    "pppSource": "consumer"
  },
  "guinea": {
    "iso3": "GIN",
    "iso2": "GN",
    "priceLevel": 0.323,
    "year": 2020,
    "pppSource": "consumer"
  },
  "guinea-bissau": {
    "iso3": "GNB",
    "iso2": "GW",
    "priceLevel": 0.378,
    "year": 2024,
    "pppSource": "consumer"
  },
  "guyana": {
    "iso3": "GUY",
    "iso2": "GY",
    "priceLevel": 0.463,
    "year": 2024,
    "pppSource": "consumer"
  },
  "haiti": {
    "iso3": "HTI",
    "iso2": "HT",
    "priceLevel": 0.809,
    "year": 2024,
    "pppSource": "consumer"
  },
  "honduras": {
    "iso3": "HND",
    "iso2": "HN",
    "priceLevel": 0.5,
    "year": 2024,
    "pppSource": "consumer"
  },
  "hong kong sar, china": {
    "iso3": "HKG",
    "iso2": "HK",
    "priceLevel": 0.748,
    "year": 2024,
    "pppSource": "consumer"
  },
  "hungary": {
    "iso3": "HUN",
    "iso2": "HU",
    "priceLevel": 0.518,
    "year": 2024,
    "pppSource": "consumer"
  },
  "iceland": {
    "iso3": "ISL",
    "iso2": "IS",
    "priceLevel": 1.131,
    "year": 2024,
    "pppSource": "consumer"
  },
  "india": {
    "iso3": "IND",
    "iso2": "IN",
    "priceLevel": 0.238,
    "year": 2024,
    "pppSource": "consumer"
  },
  "indonesia": {
    "iso3": "IDN",
    "iso2": "ID",
    "priceLevel": 0.322,
    "year": 2024,
    "pppSource": "consumer"
  },
  "iraq": {
    "iso3": "IRQ",
    "iso2": "IQ",
    "priceLevel": 0.368,
    "year": 2024,
    "pppSource": "consumer"
  },
  "ireland": {
    "iso3": "IRL",
    "iso2": "IE",
    "priceLevel": 0.955,
    "year": 2024,
    "pppSource": "consumer"
  },
  "israel": {
    "iso3": "ISR",
    "iso2": "IL",
    "priceLevel": 0.975,
    "year": 2024,
    "pppSource": "consumer"
  },
  "italy": {
    "iso3": "ITA",
    "iso2": "IT",
    "priceLevel": 0.677,
    "year": 2024,
    "pppSource": "consumer"
  },
  "jamaica": {
    "iso3": "JAM",
    "iso2": "JM",
    "priceLevel": 0.62,
    "year": 2024,
    "pppSource": "consumer"
  },
  "japan": {
    "iso3": "JPN",
    "iso2": "JP",
    "priceLevel": 0.657,
    "year": 2024,
    "pppSource": "consumer"
  },
  "jordan": {
    "iso3": "JOR",
    "iso2": "JO",
    "priceLevel": 0.452,
    "year": 2024,
    "pppSource": "consumer"
  },
  "kazakhstan": {
    "iso3": "KAZ",
    "iso2": "KZ",
    "priceLevel": 0.375,
    "year": 2024,
    "pppSource": "consumer"
  },
  "kenya": {
    "iso3": "KEN",
    "iso2": "KE",
    "priceLevel": 0.329,
    "year": 2024,
    "pppSource": "consumer"
  },
  "kiribati": {
    "iso3": "KIR",
    "iso2": "KI",
    "priceLevel": 0.617,
    "year": 2024,
    "pppSource": "consumer"
  },
  "korea, rep.": {
    "iso3": "KOR",
    "iso2": "KR",
    "priceLevel": 0.64,
    "year": 2024,
    "pppSource": "consumer"
  },
  "kosovo": {
    "iso3": "XKX",
    "iso2": "XK",
    "priceLevel": 0.406,
    "year": 2022,
    "pppSource": "consumer"
  },
  "kuwait": {
    "iso3": "KWT",
    "iso2": "KW",
    "priceLevel": 0.599,
    "year": 2024,
    "pppSource": "consumer"
  },
  "kyrgyz republic": {
    "iso3": "KGZ",
    "iso2": "KG",
    "priceLevel": 0.319,
    "year": 2024,
    "pppSource": "consumer"
  },
  "lao pdr": {
    "iso3": "LAO",
    "iso2": "LA",
    "priceLevel": 0.277,
    "year": 2024,
    "pppSource": "consumer"
  },
  "latvia": {
    "iso3": "LVA",
    "iso2": "LV",
    "priceLevel": 0.577,
    "year": 2024,
    "pppSource": "consumer"
  },
  "lebanon": {
    "iso3": "LBN",
    "iso2": "LB",
    "priceLevel": 0.585,
    "year": 2024,
    "pppSource": "consumer"
  },
  "lesotho": {
    "iso3": "LSO",
    "iso2": "LS",
    "priceLevel": 0.335,
    "year": 2024,
    "pppSource": "consumer"
  },
  "libya": {
    "iso3": "LBY",
    "iso2": "LY",
    "priceLevel": 0.374,
    "year": 2024,
    "pppSource": "consumer"
  },
  "lithuania": {
    "iso3": "LTU",
    "iso2": "LT",
    "priceLevel": 0.57,
    "year": 2024,
    "pppSource": "consumer"
  },
  "luxembourg": {
    "iso3": "LUX",
    "iso2": "LU",
    "priceLevel": 0.915,
    "year": 2024,
    "pppSource": "consumer"
  },
  "macao sar, china": {
    "iso3": "MAC",
    "iso2": "MO",
    "priceLevel": 0.63,
    "year": 2024,
    "pppSource": "consumer"
  },
  "madagascar": {
    "iso3": "MDG",
    "iso2": "MG",
    "priceLevel": 0.276,
    "year": 2024,
    "pppSource": "consumer"
  },
  "malawi": {
    "iso3": "MWI",
    "iso2": "MW",
    "priceLevel": 0.337,
    "year": 2023,
    "pppSource": "consumer"
  },
  "malaysia": {
    "iso3": "MYS",
    "iso2": "MY",
    "priceLevel": 0.317,
    "year": 2024,
    "pppSource": "consumer"
  },
  "maldives": {
    "iso3": "MDV",
    "iso2": "MV",
    "priceLevel": 0.614,
    "year": 2024,
    "pppSource": "consumer"
  },
  "mali": {
    "iso3": "MLI",
    "iso2": "ML",
    "priceLevel": 0.317,
    "year": 2024,
    "pppSource": "consumer"
  },
  "malta": {
    "iso3": "MLT",
    "iso2": "MT",
    "priceLevel": 0.632,
    "year": 2024,
    "pppSource": "consumer"
  },
  "marshall islands": {
    "iso3": "MHL",
    "iso2": "MH",
    "priceLevel": 0.952,
    "year": 2021,
    "pppSource": "consumer"
  },
  "mauritania": {
    "iso3": "MRT",
    "iso2": "MR",
    "priceLevel": 0.339,
    "year": 2023,
    "pppSource": "consumer"
  },
  "mauritius": {
    "iso3": "MUS",
    "iso2": "MU",
    "priceLevel": 0.429,
    "year": 2024,
    "pppSource": "consumer"
  },
  "mexico": {
    "iso3": "MEX",
    "iso2": "MX",
    "priceLevel": 0.59,
    "year": 2024,
    "pppSource": "consumer"
  },
  "micronesia, fed. sts.": {
    "iso3": "FSM",
    "iso2": "FM",
    "priceLevel": 0.927,
    "year": 2022,
    "pppSource": "consumer"
  },
  "moldova": {
    "iso3": "MDA",
    "iso2": "MD",
    "priceLevel": 0.47,
    "year": 2024,
    "pppSource": "consumer"
  },
  "mongolia": {
    "iso3": "MNG",
    "iso2": "MN",
    "priceLevel": 0.329,
    "year": 2024,
    "pppSource": "consumer"
  },
  "montenegro": {
    "iso3": "MNE",
    "iso2": "ME",
    "priceLevel": 0.448,
    "year": 2024,
    "pppSource": "consumer"
  },
  "morocco": {
    "iso3": "MAR",
    "iso2": "MA",
    "priceLevel": 0.406,
    "year": 2024,
    "pppSource": "consumer"
  },
  "mozambique": {
    "iso3": "MOZ",
    "iso2": "MZ",
    "priceLevel": 0.393,
    "year": 2024,
    "pppSource": "consumer"
  },
  "myanmar": {
    "iso3": "MMR",
    "iso2": "MM",
    "priceLevel": 0.315,
    "year": 2020,
    "pppSource": "consumer"
  },
  "namibia": {
    "iso3": "NAM",
    "iso2": "NA",
    "priceLevel": 0.399,
    "year": 2024,
    "pppSource": "consumer"
  },
  "nauru": {
    "iso3": "NRU",
    "iso2": "NR",
    "priceLevel": 0.859,
    "year": 2021,
    "pppSource": "consumer"
  },
  "nepal": {
    "iso3": "NPL",
    "iso2": "NP",
    "priceLevel": 0.264,
    "year": 2024,
    "pppSource": "consumer"
  },
  "netherlands": {
    "iso3": "NLD",
    "iso2": "NL",
    "priceLevel": 0.803,
    "year": 2024,
    "pppSource": "consumer"
  },
  "new caledonia": {
    "iso3": "NCL",
    "iso2": "NC",
    "priceLevel": 1.151,
    "year": 2021,
    "pppSource": "consumer"
  },
  "new zealand": {
    "iso3": "NZL",
    "iso2": "NZ",
    "priceLevel": 0.908,
    "year": 2024,
    "pppSource": "consumer"
  },
  "nicaragua": {
    "iso3": "NIC",
    "iso2": "NI",
    "priceLevel": 0.372,
    "year": 2024,
    "pppSource": "consumer"
  },
  "niger": {
    "iso3": "NER",
    "iso2": "NE",
    "priceLevel": 0.354,
    "year": 2024,
    "pppSource": "consumer"
  },
  "nigeria": {
    "iso3": "NGA",
    "iso2": "NG",
    "priceLevel": 0.18,
    "year": 2024,
    "pppSource": "consumer"
  },
  "north macedonia": {
    "iso3": "MKD",
    "iso2": "MK",
    "priceLevel": 0.377,
    "year": 2024,
    "pppSource": "consumer"
  },
  "northern mariana islands": {
    "iso3": "MNP",
    "iso2": "MP",
    "priceLevel": 0.937,
    "year": 2021,
    "pppSource": "consumer"
  },
  "norway": {
    "iso3": "NOR",
    "iso2": "NO",
    "priceLevel": 0.888,
    "year": 2024,
    "pppSource": "consumer"
  },
  "oman": {
    "iso3": "OMN",
    "iso2": "OM",
    "priceLevel": 0.481,
    "year": 2024,
    "pppSource": "consumer"
  },
  "pakistan": {
    "iso3": "PAK",
    "iso2": "PK",
    "priceLevel": 0.233,
    "year": 2024,
    "pppSource": "consumer"
  },
  "palau": {
    "iso3": "PLW",
    "iso2": "PW",
    "priceLevel": 0.993,
    "year": 2024,
    "pppSource": "consumer"
  },
  "panama": {
    "iso3": "PAN",
    "iso2": "PA",
    "priceLevel": 0.511,
    "year": 2024,
    "pppSource": "consumer"
  },
  "papua new guinea": {
    "iso3": "PNG",
    "iso2": "PG",
    "priceLevel": 0.705,
    "year": 2024,
    "pppSource": "consumer"
  },
  "paraguay": {
    "iso3": "PRY",
    "iso2": "PY",
    "priceLevel": 0.375,
    "year": 2024,
    "pppSource": "consumer"
  },
  "peru": {
    "iso3": "PER",
    "iso2": "PE",
    "priceLevel": 0.519,
    "year": 2024,
    "pppSource": "consumer"
  },
  "philippines": {
    "iso3": "PHL",
    "iso2": "PH",
    "priceLevel": 0.362,
    "year": 2024,
    "pppSource": "consumer"
  },
  "poland": {
    "iso3": "POL",
    "iso2": "PL",
    "priceLevel": 0.504,
    "year": 2024,
    "pppSource": "consumer"
  },
  "portugal": {
    "iso3": "PRT",
    "iso2": "PT",
    "priceLevel": 0.605,
    "year": 2024,
    "pppSource": "consumer"
  },
  "puerto rico (us)": {
    "iso3": "PRI",
    "iso2": "PR",
    "priceLevel": 0.897,
    "year": 2021,
    "pppSource": "consumer"
  },
  "qatar": {
    "iso3": "QAT",
    "iso2": "QA",
    "priceLevel": 0.757,
    "year": 2024,
    "pppSource": "consumer"
  },
  "romania": {
    "iso3": "ROU",
    "iso2": "RO",
    "priceLevel": 0.447,
    "year": 2024,
    "pppSource": "consumer"
  },
  "russian federation": {
    "iso3": "RUS",
    "iso2": "RU",
    "priceLevel": 0.314,
    "year": 2024,
    "pppSource": "consumer"
  },
  "rwanda": {
    "iso3": "RWA",
    "iso2": "RW",
    "priceLevel": 0.274,
    "year": 2024,
    "pppSource": "consumer"
  },
  "samoa": {
    "iso3": "WSM",
    "iso2": "WS",
    "priceLevel": 0.687,
    "year": 2024,
    "pppSource": "consumer"
  },
  "san marino": {
    "iso3": "SMR",
    "iso2": "SM",
    "priceLevel": 0.799,
    "year": 2024,
    "pppSource": "consumer"
  },
  "sao tome and principe": {
    "iso3": "STP",
    "iso2": "ST",
    "priceLevel": 0.6,
    "year": 2024,
    "pppSource": "consumer"
  },
  "saudi arabia": {
    "iso3": "SAU",
    "iso2": "SA",
    "priceLevel": 0.502,
    "year": 2024,
    "pppSource": "consumer"
  },
  "senegal": {
    "iso3": "SEN",
    "iso2": "SN",
    "priceLevel": 0.378,
    "year": 2024,
    "pppSource": "consumer"
  },
  "serbia": {
    "iso3": "SRB",
    "iso2": "RS",
    "priceLevel": 0.467,
    "year": 2024,
    "pppSource": "consumer"
  },
  "seychelles": {
    "iso3": "SYC",
    "iso2": "SC",
    "priceLevel": 0.596,
    "year": 2024,
    "pppSource": "consumer"
  },
  "sierra leone": {
    "iso3": "SLE",
    "iso2": "SL",
    "priceLevel": 0.249,
    "year": 2023,
    "pppSource": "consumer"
  },
  "singapore": {
    "iso3": "SGP",
    "iso2": "SG",
    "priceLevel": 0.78,
    "year": 2024,
    "pppSource": "consumer"
  },
  "sint maarten (dutch part)": {
    "iso3": "SXM",
    "iso2": "SX",
    "priceLevel": 0.859,
    "year": 2021,
    "pppSource": "consumer"
  },
  "slovak republic": {
    "iso3": "SVK",
    "iso2": "SK",
    "priceLevel": 0.59,
    "year": 2024,
    "pppSource": "consumer"
  },
  "slovenia": {
    "iso3": "SVN",
    "iso2": "SI",
    "priceLevel": 0.625,
    "year": 2024,
    "pppSource": "consumer"
  },
  "solomon islands": {
    "iso3": "SLB",
    "iso2": "SB",
    "priceLevel": 0.899,
    "year": 2024,
    "pppSource": "consumer"
  },
  "somalia, fed. rep.": {
    "iso3": "SOM",
    "iso2": "SO",
    "priceLevel": 0.377,
    "year": 2017,
    "pppSource": "consumer"
  },
  "south africa": {
    "iso3": "ZAF",
    "iso2": "ZA",
    "priceLevel": 0.42,
    "year": 2024,
    "pppSource": "consumer"
  },
  "south sudan": {
    "iso3": "SSD",
    "iso2": "SS",
    "priceLevel": 0.516,
    "year": 2021,
    "pppSource": "consumer"
  },
  "spain": {
    "iso3": "ESP",
    "iso2": "ES",
    "priceLevel": 0.637,
    "year": 2024,
    "pppSource": "consumer"
  },
  "sri lanka": {
    "iso3": "LKA",
    "iso2": "LK",
    "priceLevel": 0.276,
    "year": 2023,
    "pppSource": "consumer"
  },
  "st. kitts and nevis": {
    "iso3": "KNA",
    "iso2": "KN",
    "priceLevel": 0.795,
    "year": 2023,
    "pppSource": "consumer"
  },
  "st. lucia": {
    "iso3": "LCA",
    "iso2": "LC",
    "priceLevel": 0.581,
    "year": 2024,
    "pppSource": "consumer"
  },
  "st. vincent and the grenadines": {
    "iso3": "VCT",
    "iso2": "VC",
    "priceLevel": 0.633,
    "year": 2024,
    "pppSource": "consumer"
  },
  "sudan": {
    "iso3": "SDN",
    "iso2": "SD",
    "priceLevel": 0.41,
    "year": 2022,
    "pppSource": "consumer"
  },
  "suriname": {
    "iso3": "SUR",
    "iso2": "SR",
    "priceLevel": 0.443,
    "year": 2024,
    "pppSource": "consumer"
  },
  "sweden": {
    "iso3": "SWE",
    "iso2": "SE",
    "priceLevel": 0.812,
    "year": 2024,
    "pppSource": "consumer"
  },
  "switzerland": {
    "iso3": "CHE",
    "iso2": "CH",
    "priceLevel": 1.258,
    "year": 2024,
    "pppSource": "consumer"
  },
  "syrian arab republic": {
    "iso3": "SYR",
    "iso2": "SY",
    "priceLevel": 0.404,
    "year": 2021,
    "pppSource": "consumer"
  },
  "tajikistan": {
    "iso3": "TJK",
    "iso2": "TJ",
    "priceLevel": 0.285,
    "year": 2021,
    "pppSource": "consumer"
  },
  "tanzania": {
    "iso3": "TZA",
    "iso2": "TZ",
    "priceLevel": 0.253,
    "year": 2024,
    "pppSource": "consumer"
  },
  "thailand": {
    "iso3": "THA",
    "iso2": "TH",
    "priceLevel": 0.366,
    "year": 2021,
    "pppSource": "consumer"
  },
  "timor-leste": {
    "iso3": "TLS",
    "iso2": "TL",
    "priceLevel": 0.456,
    "year": 2024,
    "pppSource": "consumer"
  },
  "togo": {
    "iso3": "TGO",
    "iso2": "TG",
    "priceLevel": 0.368,
    "year": 2024,
    "pppSource": "consumer"
  },
  "tonga": {
    "iso3": "TON",
    "iso2": "TO",
    "priceLevel": 0.77,
    "year": 2024,
    "pppSource": "consumer"
  },
  "trinidad and tobago": {
    "iso3": "TTO",
    "iso2": "TT",
    "priceLevel": 0.579,
    "year": 2024,
    "pppSource": "consumer"
  },
  "tunisia": {
    "iso3": "TUN",
    "iso2": "TN",
    "priceLevel": 0.308,
    "year": 2024,
    "pppSource": "consumer"
  },
  "turkiye": {
    "iso3": "TUR",
    "iso2": "TR",
    "priceLevel": 0.383,
    "year": 2024,
    "pppSource": "consumer"
  },
  "turks and caicos islands": {
    "iso3": "TCA",
    "iso2": "TC",
    "priceLevel": 1.317,
    "year": 2021,
    "pppSource": "consumer"
  },
  "tuvalu": {
    "iso3": "TUV",
    "iso2": "TV",
    "priceLevel": 1.042,
    "year": 2024,
    "pppSource": "gdp"
  },
  "uganda": {
    "iso3": "UGA",
    "iso2": "UG",
    "priceLevel": 0.353,
    "year": 2024,
    "pppSource": "consumer"
  },
  "ukraine": {
    "iso3": "UKR",
    "iso2": "UA",
    "priceLevel": 0.269,
    "year": 2024,
    "pppSource": "consumer"
  },
  "united arab emirates": {
    "iso3": "ARE",
    "iso2": "AE",
    "priceLevel": 0.698,
    "year": 2024,
    "pppSource": "consumer"
  },
  "united kingdom": {
    "iso3": "GBR",
    "iso2": "GB",
    "priceLevel": 0.873,
    "year": 2024,
    "pppSource": "consumer"
  },
  "united states": {
    "iso3": "USA",
    "iso2": "US",
    "priceLevel": 1,
    "year": 2024,
    "pppSource": "consumer"
  },
  "uruguay": {
    "iso3": "URY",
    "iso2": "UY",
    "priceLevel": 0.729,
    "year": 2024,
    "pppSource": "consumer"
  },
  "uzbekistan": {
    "iso3": "UZB",
    "iso2": "UZ",
    "priceLevel": 0.267,
    "year": 2024,
    "pppSource": "consumer"
  },
  "vanuatu": {
    "iso3": "VUT",
    "iso2": "VU",
    "priceLevel": 1.066,
    "year": 2023,
    "pppSource": "consumer"
  },
  "viet nam": {
    "iso3": "VNM",
    "iso2": "VN",
    "priceLevel": 0.296,
    "year": 2024,
    "pppSource": "consumer"
  },
  "virgin islands (u.s.)": {
    "iso3": "VIR",
    "iso2": "VI",
    "priceLevel": 1.01,
    "year": 2021,
    "pppSource": "consumer"
  },
  "zambia": {
    "iso3": "ZMB",
    "iso2": "ZM",
    "priceLevel": 0.289,
    "year": 2024,
    "pppSource": "consumer"
  }
};
